# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:44
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rich_editor.fields


class Migration(migrations.Migration):

	dependencies = [
		('wiki', '0001_initial'),
	]

	operations = [
		migrations.AlterField(
			model_name='page',
			name='last_author',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
		),
		migrations.AlterField(
			model_name='page',
			name='parent',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='wiki.Page'),
		),
		migrations.AlterField(
			model_name='page',
			name='original_text',
			field=rich_editor.fields.RichTextOriginalField(filtered_field='filtered_text', property_name='text'),
		),
	]
