# Generated by Django 3.2.4 on 2021-06-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('wiki', '0002_auto_20170603_1644'),
	]

	operations = [
		migrations.AlterField(
			model_name='page',
			name='level',
			field=models.PositiveIntegerField(editable=False),
		),
		migrations.AlterField(
			model_name='page',
			name='lft',
			field=models.PositiveIntegerField(editable=False),
		),
		migrations.AlterField(
			model_name='page',
			name='rght',
			field=models.PositiveIntegerField(editable=False),
		),
		migrations.AlterIndexTogether(
			name='page',
			index_together={('tree_id', 'lft')},
		),
	]
