# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:44
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

	dependencies = [
		('news', '0001_initial'),
	]

	operations = [
		migrations.AlterModelManagers(
			name='news',
			managers=[
				('all_news', django.db.models.manager.Manager()),
			],
		),
	]
