# Generated by Django 3.0.10 on 2020-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('news', '0002_auto_20170603_1644'),
	]

	operations = [
		migrations.AddField(
			model_name='news',
			name='event_date',
			field=models.DateField(blank=True, null=True),
		),
	]
