# Generated by Django 3.0.8 on 2020-08-08 14:59

from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('contenttypes', '0002_remove_content_type_name'),
	]

	operations = [
		migrations.CreateModel(
			name='SearchIndex',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
				('object_id', models.PositiveIntegerField()),
				('created', models.DateTimeField(blank=True, null=True)),
				('updated', models.DateTimeField(blank=True, null=True)),
				('authors_name', models.CharField(max_length=255)),
				('language_code', models.CharField(max_length=10)),
				('title', models.TextField()),
				('document', models.TextField()),
				('comments', models.TextField()),
				('document_search_vector', django.contrib.postgres.search.SearchVectorField()),
				('comments_search_vector', django.contrib.postgres.search.SearchVectorField()),
				('combined_search_vector', django.contrib.postgres.search.SearchVectorField()),
				('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
				('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
			],
		),
		migrations.AddIndex(
			model_name='searchindex',
			index=django.contrib.postgres.indexes.GistIndex(fields=['document_search_vector'], name='fulltext_se_documen_afe45c_gist'),
		),
		migrations.AddIndex(
			model_name='searchindex',
			index=django.contrib.postgres.indexes.GistIndex(fields=['comments_search_vector'], name='fulltext_se_comment_721841_gist'),
		),
		migrations.AddIndex(
			model_name='searchindex',
			index=django.contrib.postgres.indexes.GistIndex(fields=['combined_search_vector'], name='fulltext_se_combine_ac7e09_gist'),
		),
	]
