# Generated by Django 3.2.4 on 2021-06-19 05:45

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('fulltext', '0001_initial'),
	]

	operations = [
		migrations.RemoveIndex(
			model_name='searchindex',
			name='fulltext_se_documen_afe45c_gin',
		),
		migrations.RemoveIndex(
			model_name='searchindex',
			name='fulltext_se_comment_721841_gin',
		),
		migrations.RemoveIndex(
			model_name='searchindex',
			name='fulltext_se_combine_ac7e09_gin',
		),
		migrations.AddIndex(
			model_name='searchindex',
			index=django.contrib.postgres.indexes.GinIndex(fields=['document_search_vector'], name='fulltext_se_documen_498bf9_gin'),
		),
		migrations.AddIndex(
			model_name='searchindex',
			index=django.contrib.postgres.indexes.GinIndex(fields=['comments_search_vector'], name='fulltext_se_comment_079629_gin'),
		),
		migrations.AddIndex(
			model_name='searchindex',
			index=django.contrib.postgres.indexes.GinIndex(fields=['combined_search_vector'], name='fulltext_se_combine_008edf_gin'),
		),
	]
