# Generated by Django 5.0.4 on 2024-04-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('blackhole', '0003_auto_20210619_0756'),
	]

	operations = [
		migrations.AlterIndexTogether(
			name='term',
			index_together=set(),
		),
		migrations.RemoveField(
			model_name='term',
			name='level',
		),
		migrations.RemoveField(
			model_name='term',
			name='lft',
		),
		migrations.RemoveField(
			model_name='term',
			name='rght',
		),
		migrations.RemoveField(
			model_name='term',
			name='tree_id',
		),
	]
