# Generated by Django 4.2.1 on 2023-07-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('newsletter', '0001_initial'),
	]

	operations = [
		migrations.CreateModel(
			name='MassEmailExclude',
			fields=[
				('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
			],
			options={
				'verbose_name': 'E-mail exclude',
				'verbose_name_plural': 'E-mail excludes',
			},
		),
	]
