# Generated by Django 2.1 on 2019-01-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('rating', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='rating',
			name='comment',
			field=models.TextField(blank=True, default=''),
		),
		migrations.AddField(
			model_name='rating',
			name='marked_flag',
			field=models.CharField(blank=True, choices=[('', 'Príspevok je v poriadku'), ('s', 'Spam'), ('v', 'Vulgarizmus'), ('x', 'Iné')], default='', max_length=1),
		),
		migrations.AddField(
			model_name='statistics',
			name='flag_count',
			field=models.IntegerField(default=0),
		),
	]
