# Generated by Django 2.1.5 on 2019-01-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('rating', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='rating',
			name='marked_spam',
			field=models.BooleanField(default=False),
		),
		migrations.AddField(
			model_name='statistics',
			name='spam_count',
			field=models.IntegerField(default=0),
		),
	]
