# Generated by Django 2.1 on 2019-01-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		('comments', '0002_auto_20170603_1644'),
	]

	operations = [
		migrations.AlterUniqueTogether(
			name='commentflag',
			unique_together=set(),
		),
		migrations.RemoveField(
			model_name='commentflag',
			name='comment',
		),
		migrations.RemoveField(
			model_name='commentflag',
			name='user',
		),
		migrations.DeleteModel(
			name='CommentFlag',
		),
	]
