# Generated by Django 3.2.4 on 2021-06-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('comments', '0003_auto_20190126_0840'),
	]

	operations = [
		migrations.AlterField(
			model_name='comment',
			name='level',
			field=models.PositiveIntegerField(editable=False),
		),
		migrations.AlterField(
			model_name='comment',
			name='lft',
			field=models.PositiveIntegerField(editable=False),
		),
		migrations.AlterField(
			model_name='comment',
			name='rght',
			field=models.PositiveIntegerField(editable=False),
		),
		migrations.AlterField(
			model_name='comment',
			name='user_name',
			field=models.CharField(blank=True, max_length=150),
		),
		migrations.AlterIndexTogether(
			name='comment',
			index_together={('tree_id', 'lft')},
		),
	]
