# Generated by Django 4.2.11 on 2024-04-06 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('contenttypes', '0002_remove_content_type_name'),
		('comments', '0004_auto_20210619_0756'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='comment',
			options={'ordering': ('pk',), 'verbose_name': 'komentár', 'verbose_name_plural': 'komentáre'},
		),
		migrations.AlterIndexTogether(
			name='comment',
			index_together=set(),
		),
		migrations.AlterField(
			model_name='comment',
			name='content_type',
			field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_type_set_for_%(class)s', to='contenttypes.contenttype'),
		),
		migrations.AlterField(
			model_name='comment',
			name='parent',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.comment'),
		),
		migrations.AlterField(
			model_name='comment',
			name='user',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_comments', to=settings.AUTH_USER_MODEL),
		),
		migrations.AlterIndexTogether(
			name='comment',
			index_together={('object_id', 'content_type')},
		),
		migrations.RemoveField(
			model_name='comment',
			name='level',
		),
		migrations.RemoveField(
			model_name='comment',
			name='lft',
		),
		migrations.RemoveField(
			model_name='comment',
			name='rght',
		),
		migrations.RemoveField(
			model_name='comment',
			name='tree_id',
		),
	]
