# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:44
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rich_editor.fields


class Migration(migrations.Migration):

	dependencies = [
		('forum', '0002_topic_ip_address'),
	]

	operations = [
		migrations.AlterField(
			model_name='topic',
			name='author',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
		),
		migrations.AlterField(
			model_name='topic',
			name='original_text',
			field=rich_editor.fields.RichTextOriginalField(filtered_field='filtered_text', max_length=5000, property_name='text'),
		),
		migrations.AlterField(
			model_name='topic',
			name='section',
			field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.Section'),
		),
	]
