# Generated by Django 3.2.4 on 2021-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('forum', '0003_auto_20170603_1644'),
	]

	operations = [
		migrations.AlterField(
			model_name='topic',
			name='authors_name',
			field=models.CharField(max_length=150),
		),
	]
