# Generated by Django 2.1.5 on 2019-01-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('accounts', '0003_auto_20170603_1644'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='last_name',
			field=models.CharField(blank=True, max_length=150),
		),
	]
