# Generated by Django 3.2.4 on 2021-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('accounts', '0005_auto_20190126_1152'),
	]

	operations = [
		migrations.AlterField(
			model_name='user',
			name='first_name',
			field=models.CharField(blank=True, max_length=150),
		),
	]
