# Generated by Django 4.2.1 on 2023-07-16 08:49

import django.core.validators
from django.db import migrations, models
import rich_editor.fields


class Migration(migrations.Migration):

	dependencies = [
		('accounts', '0006_alter_user_first_name'),
	]

	operations = [
		migrations.AddField(
			model_name='userrating',
			name='tweets',
			field=models.IntegerField(default=0),
		),
		migrations.AlterField(
			model_name='user',
			name='original_info',
			field=rich_editor.fields.RichTextOriginalField(blank=True, filtered_field='filtered_info', property_name='info', validators=[django.core.validators.MaxLengthValidator(100000)]),
		),
	]
