# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:44
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

	dependencies = [
		('article', '0003_series_seriesarticle'),
	]

	operations = [
		migrations.AlterModelManagers(
			name='article',
			managers=[
				('all_articles', django.db.models.manager.Manager()),
			],
		),
	]
