# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:44
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

	dependencies = [
		('blog', '0001_initial'),
	]

	operations = [
		migrations.AlterModelManagers(
			name='post',
			managers=[
				('all_objects', django.db.models.manager.Manager()),
			],
		),
		migrations.AlterField(
			model_name='post',
			name='blog',
			field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Blog'),
		),
	]
