# Generated by Django 3.2.4 on 2021-07-31 15:18
import django.db.models.deletion
import django_autoslugfield.fields
from django.db import migrations, models

import autoimagefield.fields
import linuxos.model_fields


class Migration(migrations.Migration):

	dependencies = [
		('attachment', '0003_auto_20170603_1644'),
		('blog', '0003_auto_20210711_1116'),
	]

	operations = [
		migrations.AddField(
			model_name='post',
			name='presentation_image',
			field=linuxos.model_fields.PresentationImageField(),
		),
		migrations.CreateModel(
			name='PostCategory',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
				('title', models.CharField(max_length=100)),
				('slug', django_autoslugfield.fields.AutoSlugField(in_respect_to=('blog',), title_field='title', unique=True)),
				('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
			],
			options={
				'verbose_name': 'kategória blogu',
				'verbose_name_plural': 'kategórie blogu',
			},
		),
		migrations.CreateModel(
			name='PostSeries',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
				('title', models.CharField(max_length=100)),
				('slug', django_autoslugfield.fields.AutoSlugField(in_respect_to=('blog',), title_field='title', unique=True)),
				('image', autoimagefield.fields.AutoImageField(blank=True, upload_to='blog/series/images')),
				('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
				('updated', models.DateTimeField(editable=False)),
			],
			options={
				'verbose_name': 'seriál',
				'verbose_name_plural': 'seriály',
				'unique_together': {('blog', 'slug')},
			},
		),
		migrations.AddField(
			model_name='post',
			name='category',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.postcategory'),
		),
		migrations.AddField(
			model_name='post',
			name='series',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.postseries'),
		),
		migrations.AddConstraint(
			model_name='postcategory',
			constraint=models.UniqueConstraint(condition=models.Q(('blog__isnull', True)), fields=('slug',), name='unique_blog_post_category_global_slug'),
		),
		migrations.AddConstraint(
			model_name='postcategory',
			constraint=models.UniqueConstraint(condition=models.Q(('blog__isnull', False)), fields=('blog', 'slug'), name='unique_blog_post_category_slug'),
		),
		migrations.AddField(
			model_name='postcategory',
			name='image',
			field=autoimagefield.fields.AutoImageField(blank=True, upload_to='blog/category/images'),
		),
	]
