# Generated by Django 3.2.8 on 2021-10-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('blog', '0004_auto_20210731_1718'),
	]

	operations = [
		migrations.AddField(
			model_name='blog',
			name='anonymous_comments',
			field=models.BooleanField(blank=True, null=True),
		),
		migrations.AddField(
			model_name='blog',
			name='template_css',
			field=models.TextField(blank=True, default='', max_length=1000000),
		),
		migrations.AddField(
			model_name='blog',
			name='template_settings',
			field=models.JSONField(blank=True, default=dict, editable=False),
		),
		migrations.AddField(
			model_name='blog',
			name='template_skin',
			field=models.CharField(blank=True, choices=[('', 'Nemeniť'), ('blog/simple', 'Jednoduchý')], max_length=100),
		),
	]
