# Generated by Django 2.1.5 on 2019-01-13 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('notes', '0002_auto_20170603_1644'),
	]

	operations = [
		migrations.AddField(
			model_name='note',
			name='is_public',
			field=models.BooleanField(blank=True, default=False),
		),
		migrations.AlterField(
			model_name='note',
			name='content_type',
			field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'news'), ('model', 'news')), models.Q(('app_label', 'comments'), ('model', 'comment')), models.Q(('app_label', 'forum'), ('model', 'topic')), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
		),
		migrations.AlterField(
			model_name='note',
			name='subject',
			field=models.CharField(blank=True, max_length=100),
		),
	]
