# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:44
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

	dependencies = [
		('polls', '0001_initial'),
	]

	operations = [
		migrations.AlterModelManagers(
			name='poll',
			managers=[
				('all_objects', django.db.models.manager.Manager()),
			],
		),
		migrations.AlterField(
			model_name='poll',
			name='content_type',
			field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'article'), ('model', 'article')), models.Q(('app_label', 'blog'), ('model', 'post')), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
		),
	]
