# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

	dependencies = [
		('polls', '0001_initial'),
	]

	operations = [
		migrations.AlterModelManagers(
			name='poll',
			managers=[
				('all_objects', django.db.models.manager.Manager()),
			],
		),
		migrations.AlterField(
			model_name='poll',
			name='content_type',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='typ obsahu'),
		),
	]
