# Generated by Django 2.0.6 on 2018-06-24 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_autoslugfield.fields
import rich_editor.fields


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='Tweet',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created', models.DateTimeField(editable=False, verbose_name='vytvorené')),
				('updated', models.DateTimeField(editable=False, verbose_name='upravené')),
				('title', models.CharField(max_length=255, verbose_name='titulok')),
				('slug', django_autoslugfield.fields.AutoSlugField(title_field='title', unique=True)),
				('original_text', rich_editor.fields.RichTextOriginalField(filtered_field='filtered_text', max_length=400, property_name='text', verbose_name='text')),
				('filtered_text', rich_editor.fields.RichTextFilteredField(editable=False)),
				('link_text', models.CharField(blank=True, max_length=100, verbose_name='text odkazu')),
				('link_url', models.URLField(blank=True, max_length=1000, verbose_name='odkaz')),
				('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
			],
			options={
				'verbose_name_plural': 'tweety',
				'verbose_name': 'tweet',
			},
		),
	]
