#!/bin/bash
exclude="distribute\\|psycopg2\\|oauthlib\\|python-openid\\|requests\\|requests-oauthlib\\|pyprof2calltree\\|argh\\|PyYAML\\|pathtools"
devel_packages="\
astroid\\|\
coverage\\|\
logilab\\|\
Werkzeug\\|\
django-extensions\\|\
pydot\\|\
pyparsing\\|\
pylint\\|\
django-debug-toolbar\\|\
pygraphviz\\|\
sqlparsea\\|\
ipython\\|\
watchdog"

dirname="`pwd`/`dirname $0`"
dirname=`cd "${dirname}/..";pwd`

pip freeze > ${dirname}/requirements.txt

sed -ni "/$exclude/!p" requirements.txt
cp ${dirname}/requirements.txt  ${dirname}/requirements.local.txt
sed -ni "/\\($devel_packages\\)/!p" requirements.txt
sed -ni "/\\($devel_packages\\)/p" requirements.local.txt
