#!/bin/bash
pip freeze|grep -ve "\(pylint\|astroid\|pylint-django\|pylint-plugin-utils\|logilab-common\|django-permissions-widget\|distribute\|Werkzeug\|django-extensions\|django-auth-remember\|xapian-haystack\|django-jinja\|Mako\|Paste\|WebOb\|linesman\|networkx\|pygraphviz\|django-live-profiler\|pyzmq\|statprof\)"
echo 'git+git://github.com/mireq/django-auth-remember.git#egg=django-auth-remember'
echo 'git+git://github.com/mireq/xapian-haystack.git#egg=xapian-haystack'
echo 'git+git://github.com/niwibe/django-jinja.git#egg=django-jinja'
