#!/bin/bash
set -e

DIRNAME="`pwd`/`dirname ${BASH_SOURCE:-$0}`"
DIRNAME=`cd "${DIRNAME}/..";pwd`
cd $DIRNAME
export PYTHONPATH=$DIRNAME

INSTALL=
COMPILE=

while [[ $# -gt 0 ]]
do
key="$1"
case $key in
	--compile)
	COMPILE=YES
	shift
	;;
	--install)
	INSTALL=YES
	shift
	;;
	--)
	shift
	COMPILE_ARGS=$@
	while [[ $# -gt 0 ]]
	do
		shift
	done
	;;
*)
	echo "Wrong argument $key"
	shift
	exit -1
	;;
esac
done


if [ -z $INSTALL ] && [ -z $COMPILE ]
then
	INSTALL=YES
	COMPILE=YES
fi

EXTRA_COMPILE_OPTS="-v --no-emit-index-url --annotation-style line"

if [[ -z $PYTHON_ENVIRONMENTS ]]
then
	echo "PYTHON_ENVIRONMENTS variable not set"
	echo "example: PYTHON_ENVIRONMENTS=\"3.9 3.10 3.11\""
	exit -1
fi

read -a PYTHON_ENVIRONMENTS <<< $PYTHON_ENVIRONMENTS

PYTHON_ENVIRONMENTS=$(printf ",%s" "${PYTHON_ENVIRONMENTS[@]}")
PYTHON_ENVIRONMENTS=${PYTHON_ENVIRONMENTS:1}

if [ ! -z $COMPILE ]
then
	pip_compile_universal $PYTHON_ENVIRONMENTS requirements.in $EXTRA_COMPILE_OPTS $COMPILE_ARGS
fi

if [ ! -z $INSTALL ]
then
	EXTRA_INSTALL_REQUIREMENTS=""

	if [ -f "requirements.dev.txt" ]
	then
		EXTRA_INSTALL_REQUIREMENTS="-r requirements.dev.txt"
	fi

	pip install -r requirements.txt $EXTRA_INSTALL_REQUIREMENTS
fi
