# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 14:44
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('notifications', '0001_initial'),
	]

	operations = [
		migrations.AlterField(
			model_name='event',
			name='author',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
		),
		migrations.AlterField(
			model_name='event',
			name='content_type',
			field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
		),
		migrations.AlterField(
			model_name='event',
			name='action',
			field=models.CharField(choices=[('x', 'other'), ('c', 'create'), ('u', 'update'), ('d', 'delete'), ('m', 'message'), ('a', 'comment'), ('f', 'flag')], default='m', max_length=1),
		),
		migrations.AlterModelOptions(
			name='event',
			options={'verbose_name': 'udalosť', 'verbose_name_plural': 'udalosti'},
		),
		migrations.AlterModelOptions(
			name='inbox',
			options={'verbose_name': 'schránka', 'verbose_name_plural': 'schránky'},
		),
	]
